export const OnBoardingData = [
  {
    id: 0,
    title: "Locate SAYF SPOTS",
    text: "helo",
    image: require("../assets/images/Image1.png"),
    backgroundColor: "#59b2ab",
  },
  {
    id: 1,
    title: "Meet with Friends",
    text: "helo",
    image: require("../assets/images/Image2.png"),
    backgroundColor: "#febe29",
  },
  {
    id: 2,
    title: "Have More Fun!",
    text: "helo",
    image: require("../assets/images/Image3.png"),
  },
];

export const NOTIFICATIONS_DATA = [
  {
    id: 0,
    user_image: "https://picsum.photos/id/238/200/300",
    text: "Saira Khan shared your post",
    createdAt: "8:02PM",
    name: "Saira Khan",
  },
  {
    id: 1,
    user_image: "https://picsum.photos/id/239/200/300",
    text: "Saira Khan took part in discussion",
    createdAt: "7:02PM",
    name: "Saira Khan",
  },
  {
    id: 2,
    user_image: "https://picsum.photos/id/227/200/300",
    text: "Saira Khan shared rated a loca..",
    createdAt: "4:02AM",
    name: "Saira Khan",
  },
  {
    id: 3,
    user_image: "https://picsum.photos/id/240/200/300",
    text: "Saira Khan shared your post",
    createdAt: "3:02PM",
    name: "Saira Khan",
  },
  {
    id: 4,
    user_image: "https://picsum.photos/id/545/200/300",
    text: "Saira Khan took part in discussion",
    createdAt: "2:02PM",
    name: "Saira Khan",
  },
  {
    id: 5,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
  },
  {
    id: 6,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
  },

  {
    id: 7,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
  },
  {
    id: 8,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
  },
];
export const Message_DATA = [
  {
    id: 0,
    user_image: "https://picsum.photos/id/238/200/300",
    text: "Saira Khan shared your post",
    createdAt: "8:02PM",
    name: "Saira Khan",
    message: "But, what about sunday?",
    count: "1",
  },
  {
    id: 1,
    user_image: "https://picsum.photos/id/239/200/300",
    text: "Saira Khan took part in discussion",
    createdAt: "7:02PM",
    name: "Saira Khan",
    message: "But, what about sunday?",
    count: "3",
  },
  {
    id: 2,
    user_image: "https://picsum.photos/id/227/200/300",
    text: "Saira Khan shared rated a loca..",
    createdAt: "4:02AM",
    name: "Saira Khan",
    message: "But, what about sunday?",
    count: " ",
  },
  {
    id: 3,
    user_image: "https://picsum.photos/id/240/200/300",
    text: "Saira Khan shared your post",
    createdAt: "3:02PM",
    name: "Saira Khan",
    message: "But, what about sunday?",
    count: " ",
  },
  {
    id: 4,
    user_image: "https://picsum.photos/id/545/200/300",
    text: "Saira Khan took part in discussion",
    createdAt: "2:02PM",
    name: "Saira Khan",
    message: "But, what about sunday?",
    count: " ",
  },
  {
    id: 5,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
    message: "But, what about sunday?",
    count: " ",
  },
  {
    id: 6,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
    message: "Hey, Listen!! It’s usually...?",
    count: " ",
  },

  {
    id: 7,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
    message: "50/50 chnaces, It can be either a...",
    count: " ",
  },
  {
    id: 8,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
    message: "Hey, Listen!! It’s usually...",
    count: " ",
  },
];
export const callData = [
  {
    id: 1,
    user_image: "https://picsum.photos/id/290/200/300",
    text: "Saira Khan shared rated a location",
    createdAt: "1:02PM",
    name: "Saira Khan",
    message: "Hey, Listen!! It’s usually...",
    count: " ",
    callEnd: "Call ended 3:22",
  },
];
